language: node_js

node_js:
  - "stable"
  - "node"
  - "lts/*"
  - "9"
  - "8"

notifications:
  email:
    receipients:
      - info@bytecode.nl

# before_install:

install:
  - yarn

# before_script:

script:
  - yarn run test
  - yarn run export

cache:
  yarn: true
  directories:
    - node_modules
